<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharpMind.Core\SharpMind.Core.csproj" />
    <ProjectReference Include="..\..\SharpMind.Data\SharpMind.Data.csproj" />
    <ProjectReference Include="..\..\SharpMind.Model\SharpMind.Model.csproj" />
    <ProjectReference Include="..\..\SharpMind.Tokenization\SharpMind.Tokenization.csproj" />
    <ProjectReference Include="..\..\SharpMind.Training\SharpMind.Training.csproj" />
    <ProjectReference Include="..\..\SharpMind.GPU\SharpMind.GPU.csproj" />
    <ProjectReference Include="..\..\SharpMind.CUI\SharpMind.CUI.csproj" />
  </ItemGroup>

</Project>
